= A Decorator

== Definition

A Decorator is a special kind of **declaration**  that can be attached to a:
[%step]
* class declaration, 
* method, 
* accessor, 
* property
* parameter. 


=== ...


Decorators use the form @expression, where expression must evaluate to **a function** that will be called at runtime with information about the decorated declaration.

=== Example

[source, typeScript]
----
function sealed(target) {
  // do something with 'target' ...
}
----

== Decorator Factories


If we want to customize how a decorator is applied to a declaration, we can write a decorator factory. 

=== Définition

A Decorator Factory is simply a function that returns the expression that will be called by the decorator at runtime.

=== Example

[source, typeScript]
----
function color(value: string) {
  // this is the decorator factory, it sets up
  // the returned decorator function
  return function (target) {
    // this is the decorator
    // do something with 'target' and 'value'...
  };
}
----


== Decorator Composition


Multiple decorators can be applied to a declaration:

=== Example, on a  single line

[source, typeScript]
----
@f @g x
---

=== Example, on multiple lines

[source, typeScript]
----
@f
@g
x
---

=== ...

When multiple decorators apply to a single declaration, their evaluation is similar to function composition in mathematics. 


=== ...

In this model, when composing functions f and g, the resulting composite (f ∘ g)(x) is equivalent to f(g(x)).

=== ...

As such, the following steps are performed when evaluating multiple decorators on a single declaration in TypeScript:

The expressions for each decorator are evaluated top-to-bottom.

The results are then called as functions from bottom-to-top.

=== ...

If we were to use decorator factories, we can observe this evaluation order with the following example:

== Example


[source, typeScript]
----
function first() {
  console.log("first(): factory evaluated");
  return function (target: any, propertyKey: string, descriptor: PropertyDescriptor) {
    console.log("first(): called");
  };
}
----
 
=== ...

[source, typeScript]
----
function second() {
  console.log("second(): factory evaluated");
  return function (target: any, propertyKey: string, descriptor: PropertyDescriptor) {
    console.log("second(): called");
  };
}
----


=== ...

[source, typeScript]
----
 
class ExampleClass {
  @first()
  @second()
  method() {}
}

----